# -*- coding: utf-8 -*-
"""Reto uno MINTIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k1uHw6UXpNIhDBcHnLjK-T1X-KpbMTrr
"""

j67=int(input())
m15=(2*j67)+4
r99=(3*j67+4)//5

if (r99 >= 0 and r99 <= 20):
  categoria="uno"
elif (r99 >= 21 and r99 <= 40):
  categoria="dos"
elif (r99 >= 41 and r99 <= 80):
  categoria="tres"
else:
  categoria="cuatro"

print(j67," ",m15," ",r99)
print(categoria)