# -*- coding: utf-8 -*-
"""Reto_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zSbkolKTcaQ--YYoWuAUy7AzhpW5CT8h
"""

lista=input()
lista=lista.split(",")

indices=[0]
indices.extend([i for i in range(1,len(lista)) if lista[i].lower() != lista[i-1].lower()])
indices.append(len(lista))

salida_1= " ".join([lista[indices[i-1]].upper() for i in range(1,len(indices))])
salida_2= " ".join([str(indices[i] -indices[i-1])for i in range(1,len(indices))])
print(f"\n{salida_1}\n{salida_2 }")