# -*- coding: utf-8 -*-
"""Reto 2_MisionTIC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dh8AlGbeQvkRWFzB8QSQlvM3fMzsNDbE
"""

productos_aseo=list(input())
productos_belleza=list(input())
productos_vendidos=list(input())


aseo=belleza=0
vendidos=""

for productos in productos_vendidos:
  if productos in productos_aseo and not productos in productos_belleza:
    aseo+=1
  elif productos in productos_aseo and productos in productos_belleza:
    belleza+=1
    aseo+=1
  elif not productos in productos_aseo and productos in productos_belleza:
    belleza+=1 
  if aseo>belleza:
     vendidos="A"
  elif aseo<belleza:
     vendidos="B"
  else:
    vendidos="E"

  print(vendidos,end="")