# -*- coding: utf-8 -*-
"""Reto_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Byq3pOMlpAtBz7iZbfCR1Z9aS4Ku0bp6
"""

import json

actividades=input()
actividades_zoo=json.loads(actividades)
actividades_familia=input().replace(" ",",")
actividades_familia=actividades_familia.split(",")


costo_total=0
actividades_realizar=[]



for actividad in actividades_familia:
  if actividad in actividades_zoo:
    costo_total=costo_total+actividades_zoo[actividad]
    actividades_realizar.append(actividad)


actividad_realizar=" ".join(actividades_realizar)

print(costo_total)
print(str(actividad_realizar))